language: objective-c
branches:
  only:
  - master
rvm:
- 2.2
install:
- git clone https://oktomus:${GH_TOKEN}@github.com/oktomus/boat.git -b gh-pages gh-pages
- sh ./build.install.sh
before_script:
- git config --global user.email "not-travis@travis.com"
- git config --global user.name "travis-ci"
script:
- sh ./build.web.sh
- cd gh-pages
- git add .
- git commit -m "deploy by ${TRAVIS_COMMIT}[${TRAVIS_EVENT_TYPE}]"
- git push --quiet origin gh-pages
env:
  global:
  - secure: S6D9B+cxNQ4GdVkP6xZhMj0eEDjqruidLcZ1k32zqwRmXuxuSydluXdlkE6UIjYrpeOBX9sMd3+XHBDqycwObMwFk5NAhdH4dLvhtI1SyMs9RJbwzIzp3D33hmNHDaWBM2Ed5g18cQov4KJRMlod2Z/QqqHn6Sp7405n/zWxnZHqwAOrm4abT7fXjJWptBZm0SHZKEpYW1kgfhn9fTHgiAclhJpZoExTevQtjygkcCvg1pkMpx+ZX7nh+y0AOtGb6Qy75Bj6lYF/7S2l1hRPwAvnRCbkAq05WmFWXd9xct/OI0wofvhOI9dMnz0CHM/nUwZ8M7lroQ21LQE/ekN+RQP7tJY/wX62MDQf4m7GeGBpnifdi7FfNclHHChbw5XkwuLlvZnQicQwR7aYNn9iHyg6yJFXG5M7584nr5hmFz03Q4AtkhhGQh1Zu7m3JKHvB9AbZ7XmM52EN8+u5GzgBBqpHzpupiSpGcDfLa8UofNqdxyYIFijrAI7B+2fszrTtL240OUhwkhDH1fZfhk8pQWtSrqapsjYQyD02xaIL3AIMIYt9o6FiuN3hyIyKPgh33M9Woe5Pr+u5ZjRVIlFWn2kQGGD/ekdfzaCHD3E5I31d0O8vJsGy5ousB0lLUA4ngjzd7SW+j1YW3y65Z5d6GNY9PvdORGlBlTlAtuBNkk=
  - secure: RyrSZ4sa4vvm9sy9nCJKxfJ/7nMuL6VFEBD4CGKzV+VJclmHsZuWmMlRUUVQAAU28T5u0QaT58rHrXnFeKDcaTyw11tUhXMFZ7P0pAu39tuYzWx+6pQWdFqjko5oUNuql3p6cqb0WAC3dtW3GMh8YNdclk9hNZJ7RrQE9FbNJM5A8n7KMH8hWJJD0ltIVDH4FImeXY74SZxgVo6uzsngtrsewkeqaU8e10vKH23E/vrGIggAQPcTYH+HLC4rBt88jBkwXXuRkkm9TxvMsc4iIMdaLClPziz1GTSTB7qNNjh68Gu7f4VcCDiUnMN6b52lhXqmf+OlkavBUU/o3/96czLm4QAzpbWJn/MiAHk2LLdd/wbrJigsbPNie0DKTtA1+t6f2UGfEAwA9JhRRuoUV0v1cskpsI0UesSJlmvvCsS1SeOizGdUK/qScNur96amk1AXDdrAWDFK9GFd4bdY8v+rRzoJGT64Bu4ICjvhekl96wdEthG5w+KBUYdAf/nc/O+WN6Ept1zucnQaJmQlXFvwKZWXO++RC9SveYtnN5CxtahnxyESbCLsoQaZB3MVK/Giol2UdNJPJblk10udP912izNZ+oxmDVEVThfUgSn0WZAJ9ENxZy0MmBjQ7WmPBiXrjl47UaUnTcCSQtllYDEDNGqE0SMylseahjQkmkY=
