language: objective-c
osx_image: xcode8.3
rvm:
 - 2.2
before_install:
 - chmod a+x ./buid.install.sh
 - chmod a+x ./build.web.sh
install:
 - git clone https://oktomus:${GH_TOKEN}@github.com/oktomus/boat.git -b gh-pages gh-pages
 - ./build.install.sh
 - cd gh-pages
 - git config --global user.email "hi@oktomus.com"
 - git config --global user.name "Kevin Masson"
 - git remote rm origin
 - git remote add origin https://oktomus:${GH_TOKEN}@github.com/oktomus/boat.git
 - git add .
 - git commit -m "deploy by ${TRAVIS_COMMIT}[${TRAVIS_EVENT_TYPE}]"
 - git push --quiet origin gh-pages > /dev/null 2>&1
script:
 - ./build.web.sh
